const mongoose = require("mongoose");

const attackLogSchema = new mongoose.Schema(
  {
    source: { type: String, default: "honeypot" },
    ip: { type: String, required: true, index: true },
    ipSource: { type: String, default: "socket_remote" },
    clientPublicIp: String,
    webRtcIps: [{ type: String }],
    country: String,
    countryCode: String,
    region: String,
    regionName: String,
    city: String,
    zip: String,
    timezone: String,
    lat: Number,
    lon: Number,
    geoSource: String,
    geoProvider: String,
    geoAccuracy: Number,
    geoAltitude: Number,
    geoCapturedAt: Date,
    isp: String,
    org: String,
    as: String,
    asname: String,
    isProxy: { type: Boolean, default: false },
    isHosting: { type: Boolean, default: false },
    isMobile: { type: Boolean, default: false },
    userAgent: String,
    browser: String,
    os: String,
    clientLanguage: String,
    clientPlatform: String,
    screenRes: String,
    screenAvail: String,
    canvasFingerprint: String,
    webglRenderer: String,
    connectionType: String,
    connectionDownlink: String,
    connectionRtt: String,
    batteryLevel: String,
    batteryCharging: String,
    maxTouchPoints: String,
    touchSupport: String,
    pluginsCount: String,
    colorDepth: String,
    pixelRatio: String,
    clientVendor: String,
    clientHardwareConcurrency: String,
    clientMemory: String,
    cookiesEnabled: String,
    doNotTrack: String,
    referrer: String,
    pageUrl: String,
    method: String,
    path: { type: String, index: true },
    trapPage: String,
    trapAction: String,
    headers: { type: Object, default: {} },
    query: { type: Object, default: {} },
    body: { type: Object, default: {} },
    attackTypes: [{ type: String }],
    classification: {
      type: String,
      enum: ["normal", "suspicious", "malicious"],
      default: "normal",
      index: true,
    },
    riskScore: { type: Number, default: 0, index: true },
    rateCount: Number,
    rateAnomaly: String,
    bruteForce: Boolean,
    notes: String,
  },
  { timestamps: true }
);

attackLogSchema.index({ createdAt: -1 });

module.exports = mongoose.model("AttackLog", attackLogSchema);
